### ISSUE TITLE
devtools not installed

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/fn-prevalence-predictor-mgcv#1]
This might be the culprit in it currently not running:

https://github.com/disarm-platform/fn-prevalence-predictor-mgcv/blob/f3c66baa16e37230804ce4c5a74743b3c11fc12e/function/install_packages.R#L11

I can't remember if our base image already includes this, but I suspect not...

**Comment by HughSt** [comment]
Yep, very likely. Strange that it works when I test the local container. Don't think I ran as shrinkwrap but I could be wrong..

**Comment by onlyjsmith** [comment]
I'm looking at it now, building on a remote server.

It think it would definitely run locally on your machine without that included. The best test is running in a container on your machine before you deploy.

**Comment by onlyjsmith** [comment]
Ah - sorry, re-read. You said it did work in a local _container_?

**Comment by HughSt** [comment]
Yes. But I might have built with shrinkwrap

**Comment by onlyjsmith** [comment]
Right - so that won't do any container stuff, it just collates the required files into the right folder structure. Is excellent for running against your local R.

I don't think the container would build properly if it's relying on `devtools` and we're not installing it. I'm waiting for remote build to complete.

**Comment by onlyjsmith** [comment]
Ok. Deployed version works (tested with `layer_names` and without)
- added `devtools` as a dependency
- added timeouts to the `stack.yml`
- added `scale_to_zero` setting to `stack.yml`
